routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * authentication routes
 */
Auth::routes();
Route::get('/', function () {
    return redirect('home');
});
/*****
 * website routes
 */
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/course', 'HomeController@courses')->name('course');
Route::get('/download/{id}', 'HomeController@download');
Route::get('/course-detailes/{id}', 'HomeController@courseDetails')->name('courseDetails');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/contact-us', 'HomeController@contactUs')->name('contactUs');
Route::get('/profile', 'HomeController@profile')->name('profile');
Route::post('/search_cat','HomeController@search_cat')->name('searchCat');
Route::post('/message','HelpController@sendMsg')->name('message');


Route::get('/registertrainee/{id}','TraineeController@register')->name('courseRegister');
Route::get('/closeregistertrainee/{id}','TraineeController@closeregister');
Route::resource('photo', 'PhotoController');
/*****
 * dashboard routes
 */
Route::get('/dashboard', 'DashboardController@index')->middleware('auth');
Route::resource('users', 'UserController')->middleware('auth');
Route::post('users/search','UserController@search')->name('users.search')->middleware('auth');
Route::resource('trainee', 'TraineeController')->middleware('auth');
Route::post('trainee/search','TraineeController@search')->name('trainee.search')->middleware('auth');
//Route::get('trainee/view','TraineeController@view')->name('trainee.view');

//Route::get('trainee/view', 'TraineeController@view')->name('trainee.view');

Route::resource('coach', 'CoachController')->middleware('auth');
Route::post('coach/search','CoachController@search')->name('coach.search')->middleware('auth');

Route::resource('courses','CourseController')->middleware('auth');
Route::post('courses/search','CourseController@search')->name('courses.search')->middleware('auth');

Route::resource('certificates','CertificateController')->middleware('auth');
Route::post('certificates/search','CertificateController@search')->name('certificates.search')->middleware('auth');
Route::get('certificates/print/{id}','CertificateController@print')->name('certificates.print')->middleware('auth');

 Route::get('user_courses/getDetails/{id}', 'User_CourseController@getDetails')->name('getDetails');
 Route::get('user_courses/getValue/{id}', 'User_CourseController@getValue')->name('getValue');

Route::resource('user_courses','User_CourseController');
Route::post('user_courses/search','User_CourseController@search')->name('user_courses.search');

Route::resource('receipts','ReceiptController')->middleware('auth');
Route::get('receipts/getform/{id}', 'ReceiptController@getform')->name('receipts.getform')->middleware('auth');
Route::get('receipts/print/{id}','ReceiptController@print')->name('receipts.print')->middleware('auth');

Route::resource('mangment','HomePageController')->middleware('auth');
Route::resource('mangment_fq','FaqController')->middleware('auth');
Route::resource('mangment_about','AboutUsController')->middleware('auth');
Route::resource('mangment_footer','FooterController')->middleware('auth');

Route::resource('course_trainee','CourseTraineeController')->middleware('auth');
Route::resource('course_coach','CourseCoachController')->middleware('auth');

Route::resource('user_course_message','CoachMessagesController')->middleware('auth');

Route::resource('files','FilesController')->middleware('auth');
Route::post('course/media', 'FilesController@storeMedia')
    ->name('course.storeMedia')->middleware('auth');
Route::post('course/deletemedia', 'FilesController@deleteMedia')
    ->name('course.deleteMedia')->middleware('auth');
Route::resource('exam','ExamController')->middleware('auth');
Route::get('/exam/{id}/start','HomeController@getExam')->middleware('auth');
Route::get('/join/{id}','HomeController@join')->middleware('auth');

Route::get('/ZoomMeeting',function (){
    return view('dashboard.live');
})->name('meeting')->middleware('auth');
Route::get('/zoomInit',function () {
    return view('dashboard.zoom');
})->middleware('auth');
Route::get('hostMeeting/{id}','MeetingController@startMeeting')->middleware('auth');
Route::resource('meeting','MeetingController')->middleware('auth');
Route::get('createMeeting','MeetingController@createMeeting')->middleware('auth');

Route::patch('updateMeeting/{id}','MeetingController@updateMeeting')->middleware('auth');
Route::post('exams/{id}','HomeController@getExamResult')->middleware('auth');
Route::resource('category','categoryController')->middleware('auth');
Route::post('/rate/{id}/{course}','HomeController@saveRate');
Route::resource('comment','commentController');
Route::post('getUserCourses','CertificateController@getUserCourses');
Route::get('getCertificates','CertificateController@getCertificates')->middleware('auth');
Route::get('getExams','ExamController@getExams')->middleware('auth');

Route::resource('messages','MessageController');
Route::post('getAvailableTime','CourseController@getAvailableTime');
Route::get('/getCoursePrice/{course:code}','CourseController@getPrice');

app/Meeting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Meeting extends Model
{
    //
    protected $guarded=[];
    public $timestamps=false;
    protected $dates=['start_time'];
    public function course(){
        return $this->belongsTo(Course::class);
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;
use App\Course;
use Carbon\Carbon;

class DashboardController extends Controller
{

    /**
     * Show the application home page.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $today = Carbon::now();
        $trainees= User::where('role','trainee')
                         ->whereMonth('created_at',$today)
                          ->whereYear('created_at',$today)
                          ->get();
        $trainees_all = User::where('role','trainee')->get();
        $coaches= User::where('role','coach')
                         ->whereMonth('created_at',$today)
                          ->whereYear('created_at',$today)
                          ->get();
        $coaches_all = User::where('role','coach')->get();

        $courses= Course::whereMonth('created_at',$today)
                          ->whereYear('created_at',$today)
                          ->get();
        $courses_all = Course::all();

        $categories= Course::select('category', \DB::raw('count(*) as total'))->groupBy('category')->get();

       $last_courses=Course::orderBy('created_at', 'desc')->take(4)->get();
       $last_trainees = User::where('role','trainee')->take(5)->get();

        return view('dashboard.layout.landing',['trainees'=>count($trainees),
                                              'trainees_all'=>count($trainees_all),
                                               'coaches'=>count($coaches),
                                              'coaches_all'=>count($coaches_all),
                                               'courses'=>count($courses),
                                              'courses_all'=>count($courses_all),
                                            'categories'=>count($categories),
                                            'last_courses'=>($last_courses),
                                          'last_trainees'=>($last_trainees)]);
    }


}

app/Http/Controllers/MeetingController.php
<?php

namespace App\Http\Controllers;


use App\Meeting;
use App\Traits\ZoomMeetingTrait;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MeetingController extends Controller
{
    use ZoomMeetingTrait;

    const MEETING_TYPE_INSTANT = 1;
    const MEETING_TYPE_SCHEDULE = 2;
    const MEETING_TYPE_RECURRING = 3;
    const MEETING_TYPE_FIXED_RECURRING_FIXED = 8;

    public function index()
    {
        $ids=[];
        if(Auth::user()->role=='coach')
        {
            foreach (Auth::user()->coachCourses as $course)
                array_push($ids,$course->id);
        }

        $meetings=Meeting::whereIn('course_id',$ids)->orderBy('id','desc')->paginate(10);
        return view('dashboard.meetings.list',compact('meetings'));
    }
    public function show($id)
    {
        $meeting = $this->get($id);

        return view('meetings.index', compact('meeting'));
    }

    public function createMeeting()
    {
        return view('dashboard.meetings.form');
    }
public function edit(Meeting $meeting)
{
    return view('dashboard.meetings.form',compact('meeting'));
}
    public function store(Request $request)
    {
       // dd();
        $res=$this->create($request->all());
       // dd(now())
        Meeting::create([
           'meeting_id'=>$res['data']['id'],
            'password'=>$res['data']['encrypted_password'],
            'start_time'=>new \DateTime($request->start_time),
            'course_id'=>$request->course_id,
            'topic'=>$request->topic,
            'duration'=>$request->duration
        ]);

        return redirect('meeting');
    }

    public function updateMeeting($id, Request $request)
    {
        $meeting=Meeting::find($id);
        $res=$this->update($meeting->meeting_id, $request->all());
        //dd($meeting);

        $meeting->update([
            'start_time'=>new \DateTime($request->start_time),
            'course_id'=>$request->course_id,
            'topic'=>$request->topic,
            'duration'=>$request->duration
        ]);
        return redirect('meeting');
    }

    public function destroy(Meeting $meeting)
    {
        $this->delete($meeting->meeting_id);
        $meeting->delete();

        return redirect('meeting');
    }

    public function startMeeting($id){
        $meeting=Meeting::find($id);
        $role=1;
        return view('dashboard.zoom',compact('meeting','role'));
    }
}

resources/views/dashboard/meetings/form.blade.php
@extends('dashboard.layout.master')
@section('content')
    <div class="row">
        <form
            @if(isset($meeting)&&$meeting->id)
            action="/updateMeeting/{{$meeting->id}}"
            @else action="{{route('meeting.store')}}"
            @endif
            enctype="multipart/form-data"
            method="POST"
            class="add-form w-100">
            @if(isset($meeting)&&isset($meeting->id))
                @method('PATCH')
            @endif


            <div class="col-md-12">
                <div class="card">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">

                            يوجد هناك بعض المشاكل

                            <ul>

                                @foreach ($errors->all() as $error)

                                    <li>{{ $error }}</li>

                                @endforeach

                            </ul>

                        </div>

                    @endif
                    <div class="card-header card-header-primary">
                        @if(!isset($meeting->id))
                            <h4 class="card-title">إضافة جديد</h4>
                        @else
                            <h4 class="card-title">تعديل</h4>
                        @endif
                        <p class="card-category"></p>
                    </div>
                    <div class="card-body">
                        @csrf
                        <div class="row">
                            <div class="col-md-6 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating"> موضوع الجلسة </label>
                                    <input type="text" class="form-control" name="topic"
                                           @if(isset($meeting) && $meeting->topic) value="{{$meeting->topic}}"
                                           @else value="{{ old('topic') }}" @endif
                                           required>
                                </div>
                            </div>
                            <div class="col-md-6 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating"> الدورة  </label>

                                    <select  name="course_id" class="form-control" required>
                                        <option value=''></option>
                                        @foreach(Auth::user()->coachCourses as $course)
                                            <option value='{{$course->id}}' @if(isset($meeting) && $meeting->course_id==$course->id) selected @endif>
                                                {{$course->name}}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating"> موعد بداية الجلسة  </label>
                                    <input type="datetime-local" class="form-control" name="start_time"
                                           @if(isset($meeting) && $meeting->start_time) value="{{$meeting->start_time->format('Y-m-d\TH:i:s')}}"
                                           @else value="{{ old('start_time') }}" @endif
                                           required>
                                </div>
                            </div>
                            <div class="col-md-6 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating"> مدة الجلسة </label>
                                    <input type="number" min="0" class="form-control" name="duration"
                                           @if(isset($meeting) && $meeting->duration) value="{{$meeting->duration}}"
                                           @else value="{{ old('duration') }}" @endif
                                           required>
                                </div>
                            </div>


                        </div>
                        <button type="submit" class="btn btn-primary pull-right">حفظ</button>

                        <a type="btn" class="btn btn-default pull-right" href="{{route('meeting.index')}}" >
                            إلغاء
                        </a>

                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <hr>

        </form>
    </div>

@endsection

resources/views/dashboard/meetings/list.blade.php
@extends('dashboard.layout.master')
@section('content')
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-header card-header-info">

                    <h4 class="card-title header-table-list"> قائمة جلسات البث المباشر </h4>

                    <a

                        href="/createMeeting"


                        style="float: left" alt="  إضافة جلسة">
                        <button class="btn btn-warning btn-round  glyphicon glyphicon-plus">
                            <i class="material-icons  glyphicon glyphicon-plus">add </i>
                        </button>
                    </a>
                </div>
                @if(!isset($message))
                    <div class="card-body table-responsive">
                        <table class="table table-hover">
                            <thead class="text-primary">
                            <th>#</th>
                            <th> موضوع الجلسة </th>
                            <th>الدورة  </th>
                            <th>موعد الجلسة </th>
                            <th>مدة الجلسة</th>
                            <th>  </th>
                            </thead>
                            <tbody>
                            @foreach($meetings as $meeting)
                                <tr>
                                    <td>{{$loop->index+1}}</td>
                                    <td>{{$meeting->topic}}</td>
                                    <td>{{$meeting->course->name}}</td>
                                    <td>{{$meeting->start_time}} </td>
                                    <td>{{$meeting->duration}} </td>
                                    <td style="display: flex">
                                        <a class="btn btn-primary float-right col-3 btn-edit text-success"

                                           href="/hostMeeting/{{$meeting->id}}"
                                        >

                                            <i class="material-icons">live_tv</i>
                                        </a>
                                        <a class="btn btn-primary float-right col-3 btn-edit text-success"

                                           href="{{route('meeting.edit',$meeting->id)}}"
                                        >

                                            <i class="material-icons">edit</i>
                                        </a>
                                        <form method ="post"

                                              action="{{route('meeting.destroy',$meeting->id)}}"

                                              class="col-3">
                                            <div class ="input-group">
                                                @method('DELETE')
                                                @csrf
                                                <button class="btn btn-delete float-right text-danger" onclick="confirmation($(this).parent().parent())">
                                                    <i class="material-icons">delete</i>
                                                </button>
                                            </div>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{ $meetings->links() }}
                @else
                    <div class="col-12 float-left text-danger text-center">
                        <strong>{{$message}}</strong>
                    </div>

                @endif
            </div>
        </div>
    </div>
    <script>
        function confirmation(form){
            var result = confirm("هل أنت متأكد من عملية الحذف؟");
            if(result){
                form.submit();
            }
        }
    </script>
@endsection