routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * authentication routes
 */
Auth::routes();
Route::get('/', function () {
    return redirect('home');
});
/*****
 * website routes
 */
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/course', 'HomeController@courses')->name('course');
Route::get('/download/{id}', 'HomeController@download');
Route::get('/course-detailes/{id}', 'HomeController@courseDetails')->name('courseDetails');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/contact-us', 'HomeController@contactUs')->name('contactUs');
Route::get('/profile', 'HomeController@profile')->name('profile');
Route::post('/search_cat','HomeController@search_cat')->name('searchCat');
Route::post('/message','HelpController@sendMsg')->name('message');


Route::get('/registertrainee/{id}','TraineeController@register')->name('courseRegister');
Route::get('/closeregistertrainee/{id}','TraineeController@closeregister');
Route::resource('photo', 'PhotoController');
/*****
 * dashboard routes
 */
Route::get('/dashboard', 'DashboardController@index')->middleware('auth');
Route::resource('users', 'UserController')->middleware('auth');
Route::post('users/search','UserController@search')->name('users.search')->middleware('auth');
Route::resource('trainee', 'TraineeController')->middleware('auth');
Route::post('trainee/search','TraineeController@search')->name('trainee.search')->middleware('auth');
//Route::get('trainee/view','TraineeController@view')->name('trainee.view');

//Route::get('trainee/view', 'TraineeController@view')->name('trainee.view');

Route::resource('coach', 'CoachController')->middleware('auth');
Route::post('coach/search','CoachController@search')->name('coach.search')->middleware('auth');

Route::resource('courses','CourseController')->middleware('auth');
Route::post('courses/search','CourseController@search')->name('courses.search')->middleware('auth');

Route::resource('certificates','CertificateController')->middleware('auth');
Route::post('certificates/search','CertificateController@search')->name('certificates.search')->middleware('auth');
Route::get('certificates/print/{id}','CertificateController@print')->name('certificates.print')->middleware('auth');

 Route::get('user_courses/getDetails/{id}', 'User_CourseController@getDetails')->name('getDetails');
 Route::get('user_courses/getValue/{id}', 'User_CourseController@getValue')->name('getValue');

Route::resource('user_courses','User_CourseController');
Route::post('user_courses/search','User_CourseController@search')->name('user_courses.search');

Route::resource('receipts','ReceiptController')->middleware('auth');
Route::get('receipts/getform/{id}', 'ReceiptController@getform')->name('receipts.getform')->middleware('auth');
Route::get('receipts/print/{id}','ReceiptController@print')->name('receipts.print')->middleware('auth');

Route::resource('mangment','HomePageController')->middleware('auth');
Route::resource('mangment_fq','FaqController')->middleware('auth');
Route::resource('mangment_about','AboutUsController')->middleware('auth');
Route::resource('mangment_footer','FooterController')->middleware('auth');

Route::resource('course_trainee','CourseTraineeController')->middleware('auth');
Route::resource('course_coach','CourseCoachController')->middleware('auth');

Route::resource('user_course_message','CoachMessagesController')->middleware('auth');

Route::resource('files','FilesController')->middleware('auth');
Route::post('course/media', 'FilesController@storeMedia')
    ->name('course.storeMedia')->middleware('auth');
Route::post('course/deletemedia', 'FilesController@deleteMedia')
    ->name('course.deleteMedia')->middleware('auth');
Route::resource('exam','ExamController')->middleware('auth');
Route::get('/exam/{id}/start','HomeController@getExam')->middleware('auth');
Route::get('/join/{id}','HomeController@join')->middleware('auth');

Route::get('/ZoomMeeting',function (){
    return view('dashboard.live');
})->name('meeting')->middleware('auth');
Route::get('/zoomInit',function () {
    return view('dashboard.zoom');
})->middleware('auth');
Route::get('hostMeeting/{id}','MeetingController@startMeeting')->middleware('auth');
Route::resource('meeting','MeetingController')->middleware('auth');
Route::get('createMeeting','MeetingController@createMeeting')->middleware('auth');

Route::patch('updateMeeting/{id}','MeetingController@updateMeeting')->middleware('auth');
Route::post('exams/{id}','HomeController@getExamResult')->middleware('auth');
Route::resource('category','categoryController')->middleware('auth');
Route::post('/rate/{id}/{course}','HomeController@saveRate');
Route::resource('comment','commentController');
Route::post('getUserCourses','CertificateController@getUserCourses');
Route::get('getCertificates','CertificateController@getCertificates')->middleware('auth');
Route::get('getExams','ExamController@getExams')->middleware('auth');

Route::resource('messages','MessageController');
Route::post('getAvailableTime','CourseController@getAvailableTime');
Route::get('/getCoursePrice/{course:code}','CourseController@getPrice');

app/Receipt.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Receipt extends Model
{
     public function user_course(){

    	return $this->belongsTo('App\User_Course');
    }

     protected $fillable = ['name_trainee_ar',
                             'name_trainee_en',
                             'national_id',
                             'code_trainee',
                             'code_course',
                             'date_receipt',
                             'money_payed',
                             'name_admin'
       ];
   protected $hidden = [
         'remember_token',];
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;
use App\Course;
use Carbon\Carbon;

class DashboardController extends Controller
{

    /**
     * Show the application home page.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $today = Carbon::now();
        $trainees= User::where('role','trainee')
                         ->whereMonth('created_at',$today)
                          ->whereYear('created_at',$today)
                          ->get();
        $trainees_all = User::where('role','trainee')->get();
        $coaches= User::where('role','coach')
                         ->whereMonth('created_at',$today)
                          ->whereYear('created_at',$today)
                          ->get();
        $coaches_all = User::where('role','coach')->get();

        $courses= Course::whereMonth('created_at',$today)
                          ->whereYear('created_at',$today)
                          ->get();
        $courses_all = Course::all();

        $categories= Course::select('category', \DB::raw('count(*) as total'))->groupBy('category')->get();

       $last_courses=Course::orderBy('created_at', 'desc')->take(4)->get();
       $last_trainees = User::where('role','trainee')->take(5)->get();

        return view('dashboard.layout.landing',['trainees'=>count($trainees),
                                              'trainees_all'=>count($trainees_all),
                                               'coaches'=>count($coaches),
                                              'coaches_all'=>count($coaches_all),
                                               'courses'=>count($courses),
                                              'courses_all'=>count($courses_all),
                                            'categories'=>count($categories),
                                            'last_courses'=>($last_courses),
                                          'last_trainees'=>($last_trainees)]);
    }


}

app/Http/Controllers/ReceiptController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Course;
use App\User;
use App\User_Course;
use App\Receipt;

class ReceiptController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $receipts= Receipt::orderBy('created_at','desc')->paginate(10);

          return view('dashboard.receipts.list',compact('receipts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $users = User::where('role','Admin')->get();
      $courses=Course::all('code','name');
      return view('dashboard.receipts.create',compact('users','courses'));

     }


     public function getform($id)
    {

        $users = User::where('role','Admin')->get();
       $usercourse = User_Course::find($id);
      return view('dashboard.receipts.form',compact('users','usercourse'));
      }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->except('_token', 'id'));
        $receipt = Receipt::create(
            $request->except('_token', 'id')
        );

        return redirect('receipts');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::where('role','Admin')->get();
         $receipt = Receipt::find($id);
        $courses=Course::all('code','name');
        $course=Course::where('code',$receipt->code_course)->first();
        $user_course = User_Course::where('code_course', $course->code)->get();
        $codes=[];
        foreach($user_course as $code){
            array_push($codes,$code->code_trainee);
        }
        $students = User:: whereIn('code',$codes)->get();
        return view('dashboard.receipts.edit',compact('receipt','users','courses','students') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Receipt::where('id', $id)->update(
            $request->except('_token', 'id','_method')
        );


        return redirect('receipts');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Receipt::find($id)->delete();
        return redirect('receipts');
    }


    public function print($id)
    {
        $receipt = Receipt::where('id', $id)->first();
        return view('dashboard.receipts.print',compact('receipt') );
    }
}

resources/views/dashboard/receipts/create.blade.php
@extends('dashboard.layout.master')
@section('content')
    <div class="row">
        <form

              action="{{route('receipts.store')}}"

               enctype="multipart/form-data"
             method="POST"
            class="add-form">



            <div class="col-md-8">
                <div class="card">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">

                            يوجد هناك بعض المشاكل

                            <ul>

                                @foreach ($errors->all() as $error)

                                    <li>{{ $error }}</li>

                                @endforeach

                            </ul>

                        </div>

                    @endif
                  <!--  <div class="card-header card-header-primary">
                        @if(!isset($course->id))
                            <h4 class="card-title">إضافة جديد</h4>
                        @else
                            <h4 class="card-title">تعديل</h4>
                        @endif
                        <p class="card-category"></p>
                    </div> -->
                    <div class="card-body">
                        {{csrf_field()}}
                        <div class="row">
                            <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label  for="national_id" class="bmd-label-floating "> الرقم الوطني </label>
                                    <input type="text" class="form-control" name="national_id"
                                           value="{{ old('national_id') }}" required
                                            >

                                </div>
                            </div>
                             <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating" for=""> الدورة  </label>
                                    <select class="form-control"  name="code_course" required id="courses">
                                        <option></option>
                                        @foreach($courses as $course)
                                            <option value="{{$course->code}}">{{$course->name}}</option>
                                        @endforeach
                                    </select>
                                </div>

                            </div>
                             <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating" for="type">المتدرب </label>
                                    <select class="form-control" id="students" name="code_trainee" required>
                                        <option></option>
                                    </select>


                                </div>
                            </div>


                            <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating"> اسم المتدرب الكامل بالعربي  </label>
                                    <input type="text" class="form-control" name="name_trainee_ar" id="name_trainee_ar" value="{{ old('name_trainee_ar') }}" required
                                        >

                                </div>
                            </div>
                            <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating"> اسم المتدرب بالإنكليزي </label>
                                    <input type="text" class="form-control" name="name_trainee_en" id="name_trainee_en" value="{{old('name_trainee_en')}}" required
                                    >
                                </div>
                            </div>
                            <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating"> تاريخ الإيصال </label>
                                    <input type="date" class="form-control" name="date_receipt" id="date_receipt" required value="{{old('date_receipt')}}"
                                    >
                                </div>
                            </div>

                            <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label  for="name_admin" class="bmd-label-floating ">اختر اسم المسؤول </label>
                                    <select class="form-control btn btn-secondary dropdown-toggle"  id="name_admin"  name="name_admin" >
                                      <option value=""></option>
                                      @foreach($users as $user)
                                     <option value="{{$user->first_name_ar." ".$user->last_name_ar}}">{{$user->first_name_ar." ".$user->last_name_ar}}</option>
                                       @endforeach
                                    </select>

                                </div>
                            </div>

                            <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating"> المبلغ المدفوع </label>
                                    <input type="text" class="form-control" name="money_payed"
                                              required id="money" value="{{old('money_payed')}}" readonly>
                                </div>
                            </div>



                        </div>
                        <button type="submit" class="btn btn-primary pull-right">حفظ</button>

                        <a type="btn" class="btn btn-default pull-right" href="{{url('receipts')}}" >
                            إلغاء
                        </a>

                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

        </form>
    </div>


@endsection
@section('scripts')
    <script>
        $(document).ready(function () {
            $('#courses').change(function(){
               if($(this).val()!="")
               {
                   $.ajax({
                      type:"get",
                      url:"/getCoursePrice/"+$(this).val(),
                      dataType:'json',
                      success:function (data) {
                          $('#money').attr('value',data.price);
                          var op="<option></option>";
                          $(data.students).each(function(i,e){
                              op+='<option value="'+e.code+'">'+e.first_name_ar+" "+e.last_name_ar+'</option>';
                          });
                          $('#students').html(op);
                      }
                   });
               }
               else{
                   $('#money').val('');
               }
            });
        });
    </script>
@endsection

resources/views/dashboard/receipts/form.blade.php
@extends('dashboard.layout.master')
@section('content')
    <div class="row">
        <form

              action="{{route('receipts.store')}}"

               enctype="multipart/form-data"
             method="POST"
            class="add-form">



            <div class="col-md-8">
                <div class="card">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">

                            يوجد هناك بعض المشاكل

                            <ul>

                                @foreach ($errors->all() as $error)

                                    <li>{{ $error }}</li>

                                @endforeach

                            </ul>

                        </div>

                    @endif
                  <!--  <div class="card-header card-header-primary">
                        @if(!isset($course->id))
                            <h4 class="card-title">إضافة جديد</h4>
                        @else
                            <h4 class="card-title">تعديل</h4>
                        @endif
                        <p class="card-category"></p>
                    </div> -->
                    <div class="card-body">
                        {{csrf_field()}}
                        <div class="row">
                            <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label  for="national_id" class="bmd-label-floating "> الرقم الوطني </label>
                                    <input type="text" class="form-control" name="national_id" value="{{ $usercourse->national_id }}">

                                </div>
                            </div>
                             <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating" for=""> رمز الدورة  </label>

                                 <input type="text" class="form-control" name="code_course"
                                           value="{{ $usercourse->code_course }}">

                                </div>

                            </div>
                             <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating" for="type">رمز المتدرب </label>
                                     <input type="text" class="form-control" name="code_trainee"
                                           value="{{ $usercourse->code_trainee }}">

                                </div>
                            </div>


                            <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating"> اسم المتدرب الكامل بالعربي  </label>
                                    <input type="text" class="form-control" name="name_trainee_ar" id="name_trainee_ar" value="{{ $usercourse->name_trainee_ar }}"
                                        >

                                </div>
                            </div>
                            <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating"> اسم المتدرب بالإنكليزي </label>
                                    <input type="text" class="form-control" name="name_trainee_en" id="name_trainee_en" value="{{$usercourse->name_trainee_en}}"
                                    >
                                </div>
                            </div>
                            <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating"> تاريخ الإيصال </label>
                                    <input type="date" class="form-control" name="date_receipt" id="date_receipt" required
                                    >
                                </div>
                            </div>

                            <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label  for="name_admin" class="bmd-label-floating ">اختر اسم المسؤول </label>
                                    <select class="form-control btn btn-secondary dropdown-toggle"  id="name_admin"  name="name_admin" >
                                      <option value=""></option>
                                      @foreach($users as $user)
                                     <option value="{{$user->first_name_ar." ".$user->last_name_ar}}">{{$user->first_name_ar." ".$user->last_name_ar}}</option>
                                       @endforeach
                                    </select>

                                </div>
                            </div>

                            <div class="col-md-4 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating"> المبلغ المدفوع </label>
                                    <input type="number" class="form-control" name="money_payed"
                                             min="1" required>
                                </div>
                            </div>



                        </div>
                        <button type="submit" class="btn btn-primary pull-right">حفظ</button>

                        <a type="btn" class="btn btn-default pull-right" href="{{url('receipts')}}" >
                            إلغاء
                        </a>

                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

        </form>
    </div>


@endsection

resources/views/dashboard/receipts/list.blade.php
@extends('dashboard.layout.master')
@section('content')
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-header card-header-info">
                    
                    <h4 class="card-title header-table-list">  قائمة الإيصالات </h4>
                    <a
                       
                        href="{{url('/receipts/create')}}"
                        
                        
                       style="float: left" alt="  إضافة دورة">
                        <button class="btn btn-warning btn-round  glyphicon glyphicon-plus">
                            <i class="material-icons  glyphicon glyphicon-plus">add </i>
                        </button>
                    </a>
                </div>
                @if(!isset($message))
                <div class="card-body table-responsive">
                    <table class="table table-hover">
                        <thead class="text-primary">
                        <th> رقم الإيصال </th>
                        <th>اسم المتدرب بالعربي  </th>
                        <th>تاريخ  الإيصال </th>
                        <th>المبلغ المدفوع </th>
                        <th> العمليات </th>
                        </thead>
                        <tbody>
                        
                            <tr>
                                 @foreach($receipts as $receipt)
                                <td>{{$receipt->id}}</td>
                                <td>{{$receipt->name_trainee_ar}}</td>
                                <td>{{$receipt->date_receipt}} </td>
                                <td>{{$receipt->money_payed}} </td>

                                <td style="display: flex">
                                   <a class="btn btn-primary float-right col-3 btn-edit text-success"
                                       
                                       href="{{route('receipts.edit',$receipt->id)}}"
                                      > 

                                        <i class="material-icons">edit</i>
                                    </a>
                                   <form method ="post"
                                          
                                          action="{{route('receipts.destroy',$receipt->id)}}"
                                          
                                          class="col-3">
                                        <div class ="input-group">
                                            @method('DELETE')
                                            <input type="hidden" value="{{ csrf_token() }}" name="_token">
                                            <button class="btn btn-delete float-right text-danger" onclick="confirmation()">
                                                <i class="material-icons">delete</i>
                                            </button>
                                        </div>
                                    </form> 
                                    <a class="btn btn-info btn-print float-right"
                                       
                                       href="{{route('receipts.print',$receipt->id)}}"
                                      ><i class="material-icons">print</i></a>
                                  
                                </td>
                            </tr>
                       @endforeach
                        </tbody>
                    </table>
                </div>
                 {{ $receipts->links() }}
                @else
                    <div class="col-12 float-left text-danger text-center">
                        <strong>{{$message}}</strong>
                    </div>

                @endif
                
            </div>
        </div>
    </div>
    <script>
        function confirmation(){
            var result = confirm("هل أنت متأكد من عملية الحذف؟");
            if(result){
                // Delete logic goes here
            }
        }
    </script>
@endsection

resources/views/dashboard/receipts/print.blade.php
@extends('dashboard.layout.master')
@section('content')
     <div class="card-body table-responsive">

        <table id='printTable' class="table table-hover">
               <thead class="text-primary">
               <th></th>
               <th></th>







              </thead>
                 <tbody>
                 <tr><td>رقم الإيصال</td> <td>{{$receipt->id}}</td></tr>

                  <tr><th>اسم المستخدم</th><td>{{$receipt->name_trainee_ar}}</td></tr>
                 <tr><th>رمز المتدرب</th><td>{{$receipt->code_trainee}}</td></tr>
                  <tr><th> رمز الدورة</th><td>{{$receipt->code_course}}</td></tr>
                 <tr><th> تاريخ الايصال </th><td>{{$receipt->date_receipt}}</td></tr>
                 <tr>  <th>المبلغ المدفوع</th><td>{{$receipt->money_payed}}</td></tr>
                 <tr><th>اسم الموظف المسؤول</th> <td>{{$receipt->name_admin}}</td></tr>

                 </tbody>

            </table>

           <a type="btn" class="btn btn-default pull-right" href="{{url('receipts')}}" >
                            إلغاء
                        </a>

                <a href="#null" onclick="printContent('printTable')" class="btn btn-primary">طباعة </a>

         </div>

 <script type="text/javascript">
<!--
function printContent(id){
str=document.getElementById(id).innerHTML
newwin=window.open('','printwin','left=100,top=100,width=400,height=400')
newwin.document.write('<HTML>\n<HEAD>\n')
newwin.document.write('<TITLE>Print Page</TITLE>\n')
newwin.document.write('<script>\n')
newwin.document.write('function chkstate(){\n')
newwin.document.write('if(document.readyState=="complete"){\n')
newwin.document.write('window.close()\n')
newwin.document.write('}\n')
newwin.document.write('else{\n')
newwin.document.write('setTimeout("chkstate()",2000)\n')
newwin.document.write('}\n')
newwin.document.write('}\n')
newwin.document.write('function print_win(){\n')
newwin.document.write('window.print();\n')
newwin.document.write('chkstate();\n')
newwin.document.write('}\n')
newwin.document.write('<\/script>\n')
newwin.document.write('</HEAD>\n')
newwin.document.write('<BODY onload="print_win()">\n')
newwin.document.write(str)
newwin.document.write('</BODY>\n')
newwin.document.write('</HTML>\n')
newwin.document.close()
}
//-->
</script>



@endsection