routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * authentication routes
 */
Auth::routes();
Route::get('/', function () {
    return redirect('home');
});
/*****
 * website routes
 */
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/course', 'HomeController@courses')->name('course');
Route::get('/download/{id}', 'HomeController@download');
Route::get('/course-detailes/{id}', 'HomeController@courseDetails')->name('courseDetails');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/contact-us', 'HomeController@contactUs')->name('contactUs');
Route::get('/profile', 'HomeController@profile')->name('profile');
Route::post('/search_cat','HomeController@search_cat')->name('searchCat');
Route::post('/message','HelpController@sendMsg')->name('message');


Route::get('/registertrainee/{id}','TraineeController@register')->name('courseRegister');
Route::get('/closeregistertrainee/{id}','TraineeController@closeregister');
Route::resource('photo', 'PhotoController');
/*****
 * dashboard routes
 */
Route::get('/dashboard', 'DashboardController@index')->middleware('auth');
Route::resource('users', 'UserController')->middleware('auth');
Route::post('users/search','UserController@search')->name('users.search')->middleware('auth');
Route::resource('trainee', 'TraineeController')->middleware('auth');
Route::post('trainee/search','TraineeController@search')->name('trainee.search')->middleware('auth');
//Route::get('trainee/view','TraineeController@view')->name('trainee.view');

//Route::get('trainee/view', 'TraineeController@view')->name('trainee.view');

Route::resource('coach', 'CoachController')->middleware('auth');
Route::post('coach/search','CoachController@search')->name('coach.search')->middleware('auth');

Route::resource('courses','CourseController')->middleware('auth');
Route::post('courses/search','CourseController@search')->name('courses.search')->middleware('auth');

Route::resource('certificates','CertificateController')->middleware('auth');
Route::post('certificates/search','CertificateController@search')->name('certificates.search')->middleware('auth');
Route::get('certificates/print/{id}','CertificateController@print')->name('certificates.print')->middleware('auth');

 Route::get('user_courses/getDetails/{id}', 'User_CourseController@getDetails')->name('getDetails');
 Route::get('user_courses/getValue/{id}', 'User_CourseController@getValue')->name('getValue');

Route::resource('user_courses','User_CourseController');
Route::post('user_courses/search','User_CourseController@search')->name('user_courses.search');

Route::resource('receipts','ReceiptController')->middleware('auth');
Route::get('receipts/getform/{id}', 'ReceiptController@getform')->name('receipts.getform')->middleware('auth');
Route::get('receipts/print/{id}','ReceiptController@print')->name('receipts.print')->middleware('auth');

Route::resource('mangment','HomePageController')->middleware('auth');
Route::resource('mangment_fq','FaqController')->middleware('auth');
Route::resource('mangment_about','AboutUsController')->middleware('auth');
Route::resource('mangment_footer','FooterController')->middleware('auth');

Route::resource('course_trainee','CourseTraineeController')->middleware('auth');
Route::resource('course_coach','CourseCoachController')->middleware('auth');

Route::resource('user_course_message','CoachMessagesController')->middleware('auth');

Route::resource('files','FilesController')->middleware('auth');
Route::post('course/media', 'FilesController@storeMedia')
    ->name('course.storeMedia')->middleware('auth');
Route::post('course/deletemedia', 'FilesController@deleteMedia')
    ->name('course.deleteMedia')->middleware('auth');
Route::resource('exam','ExamController')->middleware('auth');
Route::get('/exam/{id}/start','HomeController@getExam')->middleware('auth');
Route::get('/join/{id}','HomeController@join')->middleware('auth');

Route::get('/ZoomMeeting',function (){
    return view('dashboard.live');
})->name('meeting')->middleware('auth');
Route::get('/zoomInit',function () {
    return view('dashboard.zoom');
})->middleware('auth');
Route::get('hostMeeting/{id}','MeetingController@startMeeting')->middleware('auth');
Route::resource('meeting','MeetingController')->middleware('auth');
Route::get('createMeeting','MeetingController@createMeeting')->middleware('auth');

Route::patch('updateMeeting/{id}','MeetingController@updateMeeting')->middleware('auth');
Route::post('exams/{id}','HomeController@getExamResult')->middleware('auth');
Route::resource('category','categoryController')->middleware('auth');
Route::post('/rate/{id}/{course}','HomeController@saveRate');
Route::resource('comment','commentController');
Route::post('getUserCourses','CertificateController@getUserCourses');
Route::get('getCertificates','CertificateController@getCertificates')->middleware('auth');
Route::get('getExams','ExamController@getExams')->middleware('auth');

Route::resource('messages','MessageController');
Route::post('getAvailableTime','CourseController@getAvailableTime');
Route::get('/getCoursePrice/{course:code}','CourseController@getPrice');

app/Photo.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;


class Photo extends Model
{
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'image',
        'title',
        'created_at',
        
    ];

}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;
use App\Course;
use Carbon\Carbon;

class DashboardController extends Controller
{

    /**
     * Show the application home page.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $today = Carbon::now();
        $trainees= User::where('role','trainee')
                         ->whereMonth('created_at',$today)
                          ->whereYear('created_at',$today)
                          ->get();
        $trainees_all = User::where('role','trainee')->get();
        $coaches= User::where('role','coach')
                         ->whereMonth('created_at',$today)
                          ->whereYear('created_at',$today)
                          ->get();
        $coaches_all = User::where('role','coach')->get();

        $courses= Course::whereMonth('created_at',$today)
                          ->whereYear('created_at',$today)
                          ->get();
        $courses_all = Course::all();

        $categories= Course::select('category', \DB::raw('count(*) as total'))->groupBy('category')->get();

       $last_courses=Course::orderBy('created_at', 'desc')->take(4)->get();
       $last_trainees = User::where('role','trainee')->take(5)->get();

        return view('dashboard.layout.landing',['trainees'=>count($trainees),
                                              'trainees_all'=>count($trainees_all),
                                               'coaches'=>count($coaches),
                                              'coaches_all'=>count($coaches_all),
                                               'courses'=>count($courses),
                                              'courses_all'=>count($courses_all),
                                            'categories'=>count($categories),
                                            'last_courses'=>($last_courses),
                                          'last_trainees'=>($last_trainees)]);
    }


}

app/Http/Controllers/PhotoController.php
<?php

namespace App\Http\Controllers;

use App\Photo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class PhotoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $photos = Photo::orderBy('created_at','desc')->paginate(10);
        return view('dashboard.photos.list', ['photos'=>$photos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $photo = new Photo;
        return view('dashboard.photos.form', ['photo' => $photo]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $photo= new Photo;
       $photo->title=$request->title;
         $image = $request->file('image');
        if (isset($image)) {
            $imageName = time() . '.' . $image->getClientOriginalExtension();
            $image->move(public_path('images'), $imageName);
            $photo->image = $imageName;
           
        }
         $photo->save();
        return redirect('photo');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       /* $user = User::find($id);
        return view('dashboard.users.details', $user);*/
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $photo = Photo::find($id);
        return view('dashboard.photos.form', ['photo'=>$photo]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $photo= Photo::where('id', $id)->first();
       $photo->title=$request->title;
         $image = $request->file('image');
        if (isset($image)) {
            $imageName = time() . '.' . $image->getClientOriginalExtension();
            $image->move(public_path('images'), $imageName);
            $photo->image = $imageName;
           
        }
         $photo->save();
          return redirect('photo');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Photo::find($id)->delete();
        return redirect('photo');
    }

   
}

resources/views/dashboard/photos/form.blade.php
@extends('dashboard.layout.master')
@section('content')
    <div class="row">
        <form style="width: 100%"
            @if($photo->id)
            action="{{url('/photo/'.$photo->id)}}"
            @else
            action="{{url('/photo')}}"
            @endif
            method="post"
            enctype="multipart/form-data"
            class="add-form">

            @if(isset($photo->id))
                @method('PUT')
            @endif
            <div class="col-md-4">
                <div class="card">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">

                            يوجد هناك بعض المشاكل

                            <ul>

                                @foreach ($errors->all() as $error)

                                    <li>{{ $error }}</li>

                                @endforeach

                            </ul>

                        </div>

                    @endif
                    <div class="card-header card-header-primary">
                        @if(!isset($photo->id))
                            <h4 class="card-title">إضافة جديد</h4>
                        @else
                            <h4 class="card-title">تعديل</h4>
                        @endif
                        <p class="card-category"></p>
                    </div>
                    <div class="card-body">
                        {{csrf_field()}}
                        <div class="row">
                            <div class="col-md-12 pt-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating">الاسم</label>
                                    <input type="text" class="form-control" name="title"
                                           @if($photo && $photo->title) value="{{$photo->title}}"
                                           @else value="{{ old('title') }}" @endif required>
                                </div>
                            </div>

                        </div>
                        <button type="submit" class="btn btn-primary pull-right">حفظ</button>

                        <a type="btn" class="btn btn-default pull-right"
                           href="{{url('photo')}}" >
                            إلغاء
                        </a>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-8 pt-4">
                <div class="card card-profile">
                    <div class="">
                        <a href="javascript:;">
                            @if($photo && $photo->image)
                                <img class="" id="user-img" style="    width: 100%;" src="{{asset('/images/'.$photo->image)}}"/>
                            @else
                                <img class="" style="    width: 100%;" id="user-img" src="{{asset('imgd/faces/marc.jpg')}}"/>
                            @endif
                            <div class="add-img-icon">
                                <div class="choose_file">
                                  <span class="material-icons">
                                    center_focus_weak
                                    </span>
                                    <input name="image" id="userImg" type="file" accept="image/*"
                                           onchange="putImage()"/>
                                </div>
                            </div>

                        </a>
                    </div>

                </div>
            </div>
        </form>
    </div>
    <script>
        function showImage(src, target) {
            var fr = new FileReader();

            fr.onload = function () {
                target.src = fr.result;
            }
            fr.readAsDataURL(src.files[0]);

        }

        function putImage() {
            var src = document.getElementById("userImg");
            var target = document.getElementById("user-img");
            showImage(src, target);
        }


    </script>

@endsection

resources/views/dashboard/photos/list.blade.php
@extends('dashboard.layout.master')
@section('content')
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-header card-header-info">
           
                    <h4 class="card-title header-table-list">قائمة صور الدروس</h4>
                    <a href="{{url('/photo/create')}}"
                       style="float: left" alt=" إضافة  صورة">
                        <button class="btn btn-warning btn-round btn-just-icon">
                            <i class="material-icons">add</i>
                        </button>
                    </a>
                </div>
                @if(!isset($message))
                <div class="card-body table-responsive">
                    <table class="table table-hover">
                        <thead class="text-primary">
                        <th>المعرف</th>
                        <th>عنوان الصورة</th>
                        <th>تاريخ الإضافة</th>
                        <th></th>
                        </thead>
                        <tbody>
                        @foreach($photos as $photo)
                            <tr>
                                <td>{{$photo->id}}</td>
                                <td>{{$photo->title}} </td>
                                <td>{{$photo->date}}</td>
                                <td style="display: flex">
                                    <a class="btn btn-primary float-right col-3 btn-edit text-success"
                                       href="{{route('photo.edit',$photo->id)}}">

                                        <i class="material-icons">edit</i>
                                    </a>
                                    <form method ="post"
                                          action="{{route('photo.destroy',$photo->id)}}"
                                          class="col-3">
                                        <div class ="input-group">
                                            @method('DELETE')
                                            <input type="hidden" value="{{ csrf_token() }}" name="_token">
                                            <button class="btn btn-delete float-right text-danger" onclick="confirmation()">
                                                <i class="material-icons">delete</i>
                                            </button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {{ $photos->links() }}
                @else
                    <div class="col-12 float-left text-danger text-center">
                        <strong>{{$message}}</strong>
                    </div>

                @endif
            </div>
        </div>
    </div>
    <script>
        function confirmation(){
            var result = confirm("هل أنت متأكد من عملية الحذف؟");
            if(result){
                // Delete logic goes here
            }
        }
    </script>
@endsection